/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mechanical_gear.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mechanical_gear.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mechanical_Gear.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Gear_Hub.geometry} material={materials['Gear Hub']} />
      <mesh geometry={nodes.Central_Bore.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_1.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_2.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_3.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_4.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_5.geometry} material={materials['Dark Steel']} />
      <mesh geometry={nodes.Hub_Bolt_6.geometry} material={materials['Dark Steel']} />
    </group>
  )
}

useGLTF.preload('/mechanical_gear.glb')
