/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robotic_arm_45_elbow_horizontal_gripper.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robotic_arm_45_elbow_horizontal_gripper.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Heavy_Base.geometry} material={materials['Mechanical Core']} />
      <mesh geometry={nodes.Rotary_Turntable.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Base_Bearing.geometry} material={materials['Mechanical Core']} />
      <mesh geometry={nodes.Shoulder_Joint.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Shoulder_Housing.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Shoulder_Axle.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Upper_Arm_Core.geometry} material={materials['Mechanical Core']} />
      <mesh geometry={nodes.Upper_Arm_Armor.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Upper_Arm_Side_Plate.geometry} material={materials['Armor Plates']} />
      <mesh geometry={nodes.Elbow_Joint.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Elbow_Axle.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes['45_Degree_Downward_Forearm_Core'].geometry} material={materials['Mechanical Core']} />
      <mesh geometry={nodes['45_Degree_Forearm_Armor'].geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Forearm_Hydraulic_Cylinder.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Wrist_Joint.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Wrist_Axle.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Wrist_Horizontal_Adapter.geometry} material={materials['Mechanical Core']} />
      <mesh geometry={nodes.Horizontal_Tool_Coupler.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Gripper_Palm.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Horizontal_Finger_1_Base.geometry} material={materials['Armor Plates']} />
      <mesh geometry={nodes.Finger_1_Joint.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Horizontal_Finger_1_Tip.geometry} material={materials['Armor Plates']} />
      <mesh geometry={nodes.Finger_1_Gripping_Pad.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Horizontal_Finger_2_Base.geometry} material={materials['Armor Plates']} />
      <mesh geometry={nodes.Finger_2_Joint.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Horizontal_Finger_2_Tip.geometry} material={materials['Armor Plates']} />
      <mesh geometry={nodes.Finger_2_Gripping_Pad.geometry} material={materials['Joint Metal']} />
      <mesh geometry={nodes.Wrist_Rotation_Housing.geometry} material={materials['Mechanical Core']} />
    </group>
  )
}

useGLTF.preload('/robotic_arm_45_elbow_horizontal_gripper.glb')
