/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robo_dog_low_poly.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robo_dog_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Main_Body.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Upper_Body_Armor.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Chest_Plate.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Lower_Belly_Plate.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Spine_Joint_1.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Spine_Joint_2.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Spine_Joint_3.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Spine_Joint_4.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Neck_Pivot.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Neck_Armor.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Dog_Head.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Head_Side_Plate_L.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Head_Side_Plate_R.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Muzzle.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Nose_Sensor.geometry} material={materials['Optical Sensor']} />
      <mesh geometry={nodes.L_Optical_Sensor.geometry} material={materials['Optical Sensor']} />
      <mesh geometry={nodes.L_Sensor_Housing.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.R_Optical_Sensor.geometry} material={materials['Optical Sensor']} />
      <mesh geometry={nodes.R_Sensor_Housing.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.L_Pointed_Ear.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.R_Pointed_Ear.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Front_Left_Hip_Joint.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Left_Upper_Leg.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Front_Left_Knee.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Left_Lower_Leg.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Front_Left_Ankle.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Left_Paw.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Front_Left_Knee_Plate.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Front_Right_Hip_Joint.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Right_Upper_Leg.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Front_Right_Knee.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Right_Lower_Leg.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Front_Right_Ankle.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Front_Right_Paw.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Front_Right_Knee_Plate.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Rear_Left_Hip_Joint.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Left_Upper_Leg.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Rear_Left_Knee.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Left_Lower_Leg.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Rear_Left_Ankle.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Left_Paw.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Rear_Left_Knee_Plate.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.Rear_Right_Hip_Joint.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Right_Upper_Leg.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Rear_Right_Knee.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Right_Lower_Leg.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Rear_Right_Ankle.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Right_Paw.geometry} material={materials['Dark Armor']} />
      <mesh geometry={nodes.Rear_Right_Knee_Plate.geometry} material={materials['Mechanical Plates']} />
      <mesh geometry={nodes.L_Shoulder_Armor.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.R_Shoulder_Armor.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Tail_Segment_1.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Tail_Segment_2.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Tail_Segment_3.geometry} material={materials['Graphite Armor']} />
      <mesh geometry={nodes.Tail_Segment_4.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Tail_Actuator_1.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Tail_Actuator_2.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Tail_Actuator_3.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Central_Drive_Shaft.geometry} material={materials['Mechanical Joints']} />
      <mesh geometry={nodes.Rear_Core_Cover.geometry} material={materials['Mechanical Plates']} />
    </group>
  )
}

useGLTF.preload('/robo_dog_low_poly.glb')
