/*
Ported from pmndrs/examples "camera-scroll" (src/Model.tsx), originally
auto-generated by https://github.com/pmndrs/gltfjsx. See THIRD_PARTY_NOTICES.md.

Changes from the original:
 - model URL imported from src/assets/landing.ts (single swap point)
 - hover highlight uses the brand accent instead of "tomato"
 - the eased-playhead / bobbing math is unchanged
*/

import * as THREE from "three";
import { useEffect, useRef, useState, useMemo } from "react";
import { useGLTF, useAnimations, PerspectiveCamera, Clone } from "@react-three/drei";
import { useFrame, type ThreeElements } from "@react-three/fiber";
import { type GLTF } from "three-stdlib";

import { modelUrl } from "../../assets/landing";

const ACCENT = "#f5a524";
const color = new THREE.Color();

type GLTFResult = GLTF & {
  nodes: {
    Headphones: THREE.Mesh;
    Notebook: THREE.Mesh;
    Rocket003: THREE.Mesh;
    Roundcube001: THREE.Mesh;
    Table: THREE.Mesh;
    VR_Headset: THREE.Mesh;
    Zeppelin: THREE.Mesh;
  };
  materials: {
    M_Headphone: THREE.MeshStandardMaterial;
    M_Notebook: THREE.MeshStandardMaterial;
    M_Rocket: THREE.MeshStandardMaterial;
    M_Roundcube: THREE.MeshStandardMaterial;
    M_Table: THREE.MeshStandardMaterial;
    M_Headset: THREE.MeshStandardMaterial;
    M_Zeppelin: THREE.MeshStandardMaterial;
  };
};

type ModelProps = ThreeElements["group"] & {
  scroll: React.RefObject<number>;
  shadowMapSize?: number;
};

// Helper to find the baked center of the original geometries
const getCenter = (geometry: THREE.BufferGeometry) => {
  geometry.computeBoundingBox();
  const center = new THREE.Vector3();
  geometry.boundingBox?.getCenter(center);
  return center;
};

export default function Model({ scroll, shadowMapSize = 1024, ...props }: ModelProps) {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF(modelUrl) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  const [hovered, set] = useState<string | null>();

  // Custom models loaded from public/
  const dog = useGLTF("/robo_dog_low_poly.glb");
  const arm = useGLTF("/robotic_arm_45_elbow_horizontal_gripper.glb");
  const gear = useGLTF("/mechanical_gear.glb");

  const headphonesCenter = useMemo(() => getCenter(nodes.Headphones.geometry), [nodes]);
  const roundcubeCenter = useMemo(() => getCenter(nodes.Roundcube001.geometry), [nodes]);
  const tableCenter = useMemo(() => getCenter(nodes.Table.geometry), [nodes]);

  const extras = {
    receiveShadow: true,
    castShadow: true,
    "material-envMapIntensity": 0.2,
  };

  useEffect(() => void (actions["CameraAction.005"]!.play().paused = true), [actions]);

  // Recursively change colors for hovered objects (even complex nested groups)
  useEffect(() => {
    if (hovered) {
      const obj = group.current.getObjectByName(hovered);
      if (obj) {
        obj.traverse((child) => {
          const mesh = child as THREE.Mesh;
          if (mesh.isMesh && mesh.material) {
            // handle arrays of materials or single materials
            const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
            mats.forEach((m) => {
              const mat = m as THREE.MeshStandardMaterial;
              if (mat.color) mat.color.set("white");
            });
          }
        });
      }
    }
    document.body.style.cursor = hovered ? "pointer" : "auto";
    return () => void (document.body.style.cursor = "auto");
  }, [hovered]);

  useFrame((state) => {
    actions["CameraAction.005"]!.time = THREE.MathUtils.lerp(
      actions["CameraAction.005"]!.time,
      actions["CameraAction.005"]!.getClip().duration * scroll.current,
      0.05,
    );
    
    // Animate every direct child of the InteractiveGroup
    group.current.children[0].children.forEach((child, index) => {
      // Lerp material colors back to normal or ACCENT
      child.traverse((c) => {
        const mesh = c as THREE.Mesh;
        if (mesh.isMesh && mesh.material) {
          const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
          mats.forEach((m) => {
            const mat = m as THREE.MeshStandardMaterial;
            if (mat.color) {
              mat.color.lerp(
                color.set(hovered === child.name ? ACCENT : "#202020"),
                hovered ? 0.1 : 0.05,
              );
            }
          });
        }
      });

      // Bobbing floating animation
      const et = state.clock.elapsedTime;
      child.position.y = Math.sin((et + index * 2000) / 2) * 1;
      child.rotation.x = Math.sin((et + index * 2000) / 3) / 10;
      child.rotation.y = Math.cos((et + index * 2000) / 2) / 10;
      child.rotation.z = Math.sin((et + index * 2000) / 3) / 10;
    });
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        onPointerOver={(e) => {
          e.stopPropagation();
          // Find the direct child of this InteractiveGroup
          let target = e.object as THREE.Object3D;
          while (target && target.parent && target.parent.name !== "InteractiveGroup") {
            target = target.parent;
          }
          if (target) set(target.name);
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          set(null);
        }}
        name="InteractiveGroup"
        position={[0.06, 4.04, 0.35]}
        scale={[0.25, 0.25, 0.25]}
      >
        <group name="Headphones">
          {/* Replace Headphones with Robo Dog, shifted to the baked coordinates of the headphones */}
          <Clone object={dog.scene} position={headphonesCenter} scale={4} castShadow receiveShadow />
        </group>
        
        <mesh
          name="Notebook"
          geometry={nodes.Notebook.geometry}
          material={materials.M_Notebook}
          {...extras}
        />
        
        <mesh
          name="Rocket003"
          geometry={nodes.Rocket003.geometry}
          material={materials.M_Rocket}
          {...extras}
        />
        
        <group name="Roundcube001">
          {/* Replace Windmill/Turbine with Robotic Arm */}
          <Clone object={arm.scene} position={roundcubeCenter} scale={4} castShadow receiveShadow />
        </group>
        
        <group name="Table">
          {/* Replace Table with Mechanical Gear */}
          <Clone object={gear.scene} position={tableCenter} scale={8} castShadow receiveShadow />
        </group>
        
        <mesh
          name="VR_Headset"
          geometry={nodes.VR_Headset.geometry}
          material={materials.M_Headset}
          {...extras}
        />
        
        <mesh
          name="Zeppelin"
          geometry={nodes.Zeppelin.geometry}
          material={materials.M_Zeppelin}
          {...extras}
        />
      </group>
      
      <group
        name="Camera"
        position={[-1.78, 2.04, 23.58]}
        rotation={[1.62, 0.01, 0.11]}
      >
        <PerspectiveCamera
          makeDefault
          far={100}
          near={0.1}
          fov={28}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <directionalLight
            castShadow
            position={[10, 20, 15]}
            shadow-camera-right={8}
            shadow-camera-top={8}
            shadow-camera-left={-8}
            shadow-camera-bottom={-8}
            shadow-mapSize-width={shadowMapSize}
            shadow-mapSize-height={shadowMapSize}
            intensity={2 * Math.PI}
            shadow-bias={-0.0001}
          />
        </PerspectiveCamera>
      </group>
    </group>
  );
}

useGLTF.preload(modelUrl);
useGLTF.preload("/robo_dog_low_poly.glb");
useGLTF.preload("/robotic_arm_45_elbow_horizontal_gripper.glb");
useGLTF.preload("/mechanical_gear.glb");
